### PR TITLE
bugfixes

### PR DESCRIPTION
**Pull request by SteffenDE**
The only real bug still there in LiveView 0.20.5 is the LiveComponents breaking. See https://github.com/phoenixframework/phoenix_live_view/pull/3111.

The other problems can be fixed in your code, as described in the code comments.

### CODE REVIEW

**Comment by DaTrader** [comment]
I am happy you found and fixed the bug in v0.20.5.

As for my demo app, I have some questions here:

1. Let disregard the move thing here b/c  I accepted it not to work b/c of the breaking change introduced with `stream_insert/4`

2. Alpine integration: How come I don't need a tree initialization call in the hook's `updated` function with the v0.20.1? I have never had a need for it in the real app I am developing. 

3. The changes made to my "reset_items" handler and consequentially to the `ItemComponent.update` function are, I believe you adding some more behavior because you thought it'd be more logical to work that way - those hopefully have nothing to do with the LV stream functioning properly?

UPDATE: Now I can see in your email you mention this under no. 3. What do you mean by that - they keep their state if you reset them? Shouldn't the reset within them work anyway? Please elaborate a bit further.

@SteffenDE 

UPDATE 2: To expand on the above (still no. 3): My original intention was not for the "reset_items" in `ItemListComponent.handle/3` to reset individual streams within the `ItemComponent`s and the comment in my email to you regarding the only thing not working in v0.20.1 regarded the color reset button within the item itself (not the "Reset items" button).

**Comment by SteffenDE** [comment]
@DaTrader if you don't expect the "Reset items" button to also reset the colors inside the LiveComponents then you don't need the send_update calls and update clause I added. Probably I just misunderstood something in your email.

Concerning the Alpine update function: I'm not exactly sure why it is needed. I'm not into Alpine, but you can test yourself that it will fail after a while without it. I think it may be because the stream reset now morphes the nodes instead of leaving them as is and therefore needing to re-initialize alpine in update.

**Comment by DaTrader** [comment]
Yeah, just did and you're right, it does fail now (but didn't use to).

My problem here is that prior to 0.20 (or 0.19 I don't remember anymore), not even the `mounted` callback was needed, then I spent some time arguing with Jose' and eventually settled with the hook. Now, this concern has spread over to the `updated` callback as well. Why this bothers me is that I'm afraid those `initTree` calls may not be cheap or may have undesired side effects to the Alpine state.

**Comment by DaTrader** [comment]
Btw, just tried this latest fix on my real app. The issues are still there when resetting a stream having a subset of the new items. It behaves differently than before the latest fix, but it's still not correct. 

I always compare it what it's like on v0.20.1 and there's no doubt there are still stream reset bug(s) in the v0.20.5.

**Comment by DaTrader** [comment]
Btw 2, as far as you can tell, is the execution of the hook callbacks accounted for in logs shown after the `liveSocket.enableProfiling()`?

**Comment by SteffenDE** [comment]
@DaTrader as always, I'll need something to reproduce. So if you can adjust this repo to demonstrate the problem I can have a look.

It is expected that you see more logs with profiling enabled because LV morphs the stream items that are kept on reset.

**Comment by DaTrader** [comment]
> @DaTrader as always, I'll need something to reproduce. So if you can adjust this repo to demonstrate the problem I can have a look.

Yes, as always.

> It is expected that you see more logs with profiling enabled because LV morphs the stream items that are kept on reset.

I am not referring to that. I am asking if you know if the execution time of the hook callbacks is accounted for in those logs (as part of the execution time of the patches) or not so I can be sure the added `updated` hook callback is not taking its toll.

**Comment by SteffenDE** [comment]
I think it should be included in the _component patch complete_ time, but not in the _morphdom_ time.

**Comment by DaTrader** [comment]
Btw, do you happen to know if the following should still work on v0.20.5 b/c it works perfectly fine on v0.20.1:

```elixir
socket = stream(  socket, :stream_name, [], reset: true)

..

Enum.reduce( script, socket, fn
  %{ edit_action: { :insert_at, insert_at}} = item, socket ->
    stream_insert( socket, :stream_name, item, at: insert_at)

  # note: this will never be called when the stream is reset -it's just a reuse of the function when this may be the case
  %{ edit_action: :delete} = delete, socket ->
    stream_delete_by_dom_id( socket, :stream_name, dom_id( %{ id: delete.item_id}, myself))

  item, socket ->
    stream_insert( socket, :stream_name, item)
end)
```

**Comment by SteffenDE** [comment]
The only change with inserts should be the ordering. If you want to reorder you need to delete first. All else should be the same, I think.

**Comment by DaTrader** [comment]
Ok, but I am asking you about first a reset then the insertion.

**Comment by SteffenDE** [comment]
I don't expect any difference in that insert code.

**Comment by DaTrader** [comment]
> I don't expect any difference in that insert code.

You're right. They behave identically (equally buggy).

Now, here's something VERY interesting. I hope this helps you pinpoint the problem.

1. I pass 12 items to the `stream/4` with `reset: true` with only the 12th being new relative to what the stream is already showing (the first 11 items exist in both the old stream and the new list passed to it with the reset option). 

2. I log the id's of each item in the `:for={{ dom_id, item} <- @streams.comments}` by simply inspecting them as in `<.live_component id={ dom_id |> IO.inspect()} .. />` (the items themselves are also live components). ALL 12 get logged.

3. Now, I also log the `<div id={@id |> IO.inspect()} ..>` within the item LiveComponent template and just ONE (that last new one) is actually rendered.

So, my conclusion is this is an issue that occurs at the rendering level (in Elixir code), between the stream LiveComponent and its streamed child LiveComponent. (it's optimized from 12 to 1 </sarc> ;)

**Comment by SteffenDE** [comment]
@DaTrader if the content of the LiveComponents did not change it is expected that you only see one render call. LiveComponents that are in a stream keep their state when they are re-inserted. With re-inserted I mean that they are either deleted and inserted at the same time, or the stream is reset, but they are both in the old and the new stream.

**Comment by DaTrader** [comment]
> if the content of the LiveComponents did not change it is expected that you only see one render call.

Hold on. 

1. This makes no sense whatsoever when `reset` is set to true. 
2. If true, it is inconsistent with itself, for in the demo app when those color items get reset, they do get rendered despite their state being unchanged internally.  So, this rule seems to be in place only when some elements are present and not all of them.
3. Again if true, this is an undocumented breaking change, because this certainly isn't so in v0.20.1
4. Please, revert it back to the old behavior because of no. 1

**Comment by DaTrader** [comment]
And yes, if true, it is crazy to assume we need to artificially change the state of each individual element (e.g. something like version it?) just to make the `reset` option work.

**Comment by josevalim** [comment]
There is nothing crazy about it and it makes total sense based on how LiveComponents work. Because they are stateful, you can move a LiveComponent across different parts of the page, and its state is preserved. For example, you can move cards to different lists in a Trello board.  Moving positions in a stream is the same. Resetting a stream resets only a stream. If live components inside streams did not behave like this before, then it was a bug that needed addressing.

**Comment by josevalim** [comment]
To add to the above, if the live component is fully removed from a page, then rendering them in another cycle gets a new state. You can also force removals by giving them a new ID (you can have the ID as a tuple, the first element is the "stream-counter", which is increment on every reset).

**Comment by SteffenDE** [comment]
> UPDATE 2: To expand on the above (still no. 3): My original intention was not for the "reset_items" in ItemListComponent.handle/3 to reset individual streams within the ItemComponents and the comment in my email to you regarding the only thing not working in v0.20.1 regarded the color reset button within the item itself (not the "Reset items" button).

This is what you mentioned yesterday, which is kind of contradicting.

In your demo, you have a list of ItemComponent LiveComponents, for example:

* ItemComponent 1
* ItemComponent 2
* ItemComponent 3

The stream of items contains an `id`, `name` and `qty`. Because they are LiveComponents, they have their own internal state. Inside the LiveComponent you have the stream of colors. Now, when you "reset" the stream and add Items 1,2,3 again and also add Item 4, the LiveComponents 1,2,3 will not get re-rendered because their state did not change. Therefore the color stream is also untouched. They would re-render if you also change for example the name or quantity. This is totally expected because they are **Live**Components. So in this case only the render function of item 4 would be called.
If this is NOT what you want you can do either what I did in this PR - send a message to the LiveComponent to selectively reset their internal state - or as José mentioned give the `<.live_component` an ID that changes when you reset the stream, for example:

```
<.live_component
      :for={{ dom_id, item} <- @streams.items}
      module={LvBugs0195Web.Live.Home.ItemComponent}
      id={System.unique_integer()}
      dom_id={dom_id}
      item={item}
    />
```

Inside the component you need to add `id={dom_id}` to the root node. This would fully reset the component's state each time the stream is reset.

**Comment by DaTrader** [comment]
@josevalim 

> If live components inside streams did not behave like this before, then it was a bug that needed addressing.

I'm sorry but neither you nor Chris used to share the view that this was a bug back when I reported the original stream reset bug in https://github.com/phoenixframework/phoenix_live_view/issues/2767. It is true that Chris did not express his opinion on it, but you did take part of the discussion. There were zero mentions it was just about the ids and that the user would have to take care of the rest. My demo app stood there for a while and the participants who thought it was a misunderstanding of how the feature was supposed to work had plenty of chance to say so.

In addition, given the absence of a documented breaking change in this regard, it leads to conclusion that this is a side effect of the recent optimizations which is now being justified as what should've been the right decision from the beginning.

But that's not the worst thing about it. As you suggest yourself, using a two step/cycle reset (what I used to do before starting to hope the stream reset would eventually get fixed for real), or by introducing something like a reset counter become the only two workarounds. In that case, speaking as strictly as your views are here on what is considered a reset (essentially just the order of the streamed component ids and not a stream of components), this is not a reset, but a delete_all where, unless forcing the user to use the reset counter, the reset actually becomes the two step procedure implemented by the user themselves, which in turn becomes yet another case of "transferring" what used to be thought of as a responsibility of the framework onto the users. 

To put it in a different way, would it hurt to implement it so it's easier and more straight forward for users as opposed to misleading? Because providing a list of items to a stream and expecting it to "reset" just the ones that are not already rendered in the very stream that's supposed to be "reset" is in fact misleading, regardless of the reference to the LiveComponent lifecycle (which in my view could and should be affected by an actual stream reset). But then again, it's just me, maybe other users will be thrilled with idea when they eventually do upgrade and find out about this.

**Comment by DaTrader** [comment]
@SteffenDE 

> Now, when you "reset" the stream and add Items 1,2,3 again and also add Item 4, the LiveComponents 1,2,3 will not get re-rendered because their state did not change

Yes, that's been the desired behavior.

> This is what you mentioned yesterday, which is kind of contradicting.

So, I assume what you're referring to contradicting is me assuming the LiveComponent in the stream would get re-rendered even though its state has not changed. But why is that contradicting? It itself does not need to have its state reset first to get re-rendered.

UPDATE: I thought you said something else there under the first quote. I see where you're getting at, but I still don't see why in this particular case where one explicitly states `reset: true` it should not be treated as: render what I am supplying you with nothing more, nothing less, and if it already exists, let it keep its state but render it nevertheless.

UPDATE 2: And it rhymes, therefore it must true :)

**Comment by josevalim** [comment]
> I'm sorry but neither you nor Chris used to share the view that this was a bug back when I reported the original stream reset bug in https://github.com/phoenixframework/phoenix_live_view/issues/2767.

That's a completely separate issue to me. LiveComponents not resetting their inner state when moved around is a different issue. That issue does not even mention components at all.

> In addition, given the absence of a documented breaking change in this regard, it leads to conclusion that this is a side effect of the recent optimizations which is now being justified as what should've been the right decision from the beginning.

If you are going to assume our discussions and explanations as justifications of side-effects, rather than what we believe to be correct, then there is no point in having a discussion at all.

**Comment by DaTrader** [comment]
> That's a completely separate issue to me. LiveComponents not resetting their inner state when moved around is a different issue. That issue does not even mention components at all.

The demo app with child LiveComponents was provided there with the issue, so it's not a different issue.

**Comment by DaTrader** [comment]
> If you are going to assume our discussions and explanations as justifications of side-effects, rather than what we believe to be correct, then there is no point in having a discussion at all.

It is not about what you believe to be correct but when you started to believe it to be correct, because in the meantime many people might have get vested into a prior belief. No one is error proof (nor is expected to be), but let's call the things what they are. 

But the most important question is - what now?

**Comment by josevalim** [comment]
The positioning of elements is separate from their state, you are extrapolating a decision from one issue into another one.

Even then, it doesn't matter, we can change our minds. Everything we guarantee is written in the license, no one is even entitled to explanation.

What now has already been answered. LiveComponents moving around in a stream do not get their state reset. How many times shall we repeat the same information in the same thread?

**Comment by josevalim** [comment]
The positioning of elements is separate from their state, you are extrapolating a decision from one issue into another one. You did a report with two bugs, we said we agree with bug #1, and you are extrapolating that as an agreement to bug #2, which no one mentioned anywhere.

And of course, It should not be necessary, but I will add the disclaimer that: I may be wrong and I do not provide any guarantee that my statements here will hold truth throughout LiveView's existence.

**Comment by SteffenDE** [comment]
> UPDATE: I thought you said something else there under the first quote. I see where you're getting at, but I still don't see why in this particular case where one explicitly states `reset: true` it should not be treated as: render what I am supplying you with nothing more, nothing less, and if it already exists, let it keep its state but render it nevertheless.

I think there is maybe still a misunderstanding here. Your last sentence is correct, except for the very last part. The live component does "**render what I am supplying you with** nothing more, nothing less, and if it already exists, let it keep its state". Live Components do not render if their state does not change. When you reset the stream, the update function of your live component will be called as usual. If the result of your update function is that the state of the component did not change, then it will not re-render. So if you want to reset the inner stream on update, you can write your update function in a way that resets the stream. Currently you only assign the inner stream in the mount of the component.

> But the most important question is - what now?

The solutions have been described in this thread. So to summarize:

You can:
1. have a changing ID to force a new component to be created on reset
2. send a message to the component to handle the reset internally in the component
3. code you live component such that it resets the stream when it is updated (this is similar to 2)

**Comment by josevalim** [comment]
Also, to be fully transparent here, the behaviour being discussed here seems to have been introduced here: https://github.com/phoenixframework/phoenix_live_view/commit/beeed2e2fe3fdc7d20e33b40df505544b259bb35

The commit above was to fix a bug reported by you, #2657, because we were always deleting all stream elements and doing so made it so we always lost the client state, including live component information. As you said:

> The other is a problem with the new :reset option that I was so looking forward to. In short, any combo of using this option while also providing a list of items to stream/4 (or providing an empty list of items and then inserting the items in a loop) ends up with the client-side deletion of the items present both client-side and in the new list.

Once we fixed the bug, we fixed both client state (and live components, because they are tracked based on the client state). In fact, under expected behaviour, you did describe the current solution as acceptable:

> The :reset option should result in all except for the provided items deleted from the stream, so if some of the items are present in both the stream and the new item list, **they should simply be preserved as such**, or re-added immediately after the reset.

Emphasis mine. And later I added:

> The second one looks like a bug indeed. We may not be keeping the relevant stream information when we re-render an **existing** live component.

Emphasis mine, pointing out that the live component should be the same (i.e. existing), instead of a new one.

And of course, the bug fix is in the changelog. So, as far as I understand, **the behaviour is consistent since we fixed a bug you reported, in a way that matches the behaviour you describe as expected**.

**Comment by SteffenDE** [comment]
btw @DaTrader, was there any LiveView version that behaved the way you expect (related to streams inside LiveComponents)

**Comment by DaTrader** [comment]
> In my opinion, LiveComponents moving around in a stream do not get their state reset

Of course. Where did I root for otherwise?

As far as I can see it from your and @SteffenDE's replies the only difference that I am suggesting is that with the stream reset option set to true, the component should be rerendered regardless of whether its state has changed or not. That's it. I never implied resetting the state of a streamed component, on the contrary.

> And of course, the bug fix is in the changelog. So, as far as I understand, **the behaviour is consistent since we fixed a bug you reported, in a way that matches one of the behaviours you describe as expected** (and I agree it is the expected one).

Fair enough, but it should be stated somewhere explicitly that it's now up to the user to have the LiveComponent changed if they want them to be rerendered when the stream is reset. Plus, it won't hurt to provide those two examples of how to do it.

As a reminder - this all used to work how I see it properly in v0.20.1. It works differently now. People need to know this.

**Comment by josevalim** [comment]
> Of course. Where did I root for otherwise?

Basically this whole thread. The only reason you were seeing the previous behaviour was because the state was lost (which we now all agree was a bug). :D

**Comment by SteffenDE** [comment]
> As a reminder - this all used to work how I see it properly in v0.20.1. It works differently now. People need to know this.

When I use 0.20.1 items don't reset properly as you mentioned in your email to me.

**Comment by DaTrader** [comment]
> btw @DaTrader, was there any LiveView version that behaved the way you expect (related to streams inside LiveComponents)

Yes, in v0.20.1. The only bug there was was the one that the resetting streams in the nested live components didn't work, not from the outside as you first thought, but it didn't work from the inside - with the item component handling the event and its own stream reset.

**Comment by DaTrader** [comment]
> Basically this whole thread. The only reason you were seeing the previous behaviour was because the state was lost (which we now all agree was a bug). :D

No. The state was not lost. Try the demo app on the v0.20.1 and see for yourself.

**Comment by josevalim** [comment]
>  Try the demo app on the v0.20.1 and see for yourself.

It is running on v0.20.1 on my machine and clicking reset items does not work on inner nor outer. 🤷‍♂️

**Comment by josevalim** [comment]
> No. The state was not lost. 

State was lost on 0.19.5, which led to: beeed2e2fe3fdc7d20e33b40df505544b259bb35

Once that was fixed, I cannot get the app to reset properly, not even on v0.20.1.

**Comment by DaTrader** [comment]
> It is running on v0.20.1 on my machine and clicking reset items does not work on inner nor outer. 🤷‍♂️

So, try this just to see it in full.

1. Start the color carousel on of them just for the order to be different so you can see it won't be reset (as intended) when the outer stream is reset.
2. Prepend or append a couple of items and they click Reset items. The ones that were added will rightfully vanish, while the color component order in that one item from 1 will not be changed.

**Comment by DaTrader** [comment]
> > No. The state was not lost.
> 
> State was lost on 0.19.5, which led to: beeed2e2fe3fdc7d20e33b40df505544b259bb35
> 
> Once that was fixed, I cannot get the up to reset properly, not even on v0.20.1.

Have you pulled from the last `main`?

**Comment by SteffenDE** [comment]
> > It is running on v0.20.1 on my machine and clicking reset items does not work on inner nor outer. 🤷‍♂️
> 
> So, try this just to see it in full.
> 
> 1. Start the color carousel on of them just for the order to be different so you can see it won't be reset (as intended) when the outer stream is reset.
> 2. Prepend or append a couple of items and they click Reset items. The ones that were added will rightfully vanish, while the color component order in that one item from 1 will not be changed.

This is exactly how it works with the latest fix from `{:phoenix_live_view, github: "SteffenDE/phoenix_live_view", branch: "nested_stream_morph_assets", override: true},`, isn't it?

**Comment by DaTrader** [comment]
@josevalim Sorry, now pull the main, because I had to remove the propagation behavior that @SteffenDE added, but did not push it to github. It's there now

**Comment by josevalim** [comment]
> This is exactly how it works with the latest fix from {:phoenix_live_view, github: "SteffenDE/phoenix_live_view", branch: "nested_stream_morph_assets", override: true},, isn't it?

It is, I just double checked. I am honestly baffled that we are getting so much flack from:

1. a bug that has been fixed
2. according to a behaviour that was previously declared as expected

**Comment by josevalim** [comment]
> Sorry, now pull the main, because I had to remove the propagation behavior that @SteffenDE added, but did not push it to github. It's there now

This behaves exactly as v0.20.1 to me.

**Comment by DaTrader** [comment]
> This is exactly how it works with the latest fix from `{:phoenix_live_view, github: "SteffenDE/phoenix_live_view", branch: "nested_stream_morph_assets", override: true},`, isn't it?

Yes, but the demo app does not have a use case where just some items get reset but always all of them. In my real life app, the use case is different. Before reset the stream contains n items (live components) out of which 11 will be the same as in the list that's provided for the reset. In such a scenario, only the last one gets rendered, not all 12 of them.

While on v0.20.1 it works perfectly fine even in this regard.

**Comment by SteffenDE** [comment]
@DaTrader the 11 existing ones get removed?

**Comment by DaTrader** [comment]
> @DaTrader the 11 existing ones get removed?

Yes. As I stated before the whole discussion on LiveComponents.

**Comment by josevalim** [comment]
> Yes, but the demo app does not have a use case where just some items get reset but always all of them. 

@DaTrader so basically, the behaviour you describe cannot be seen on this demo app? Are you serious? So are you asking us to run it on main if it does not show the bug?

**Comment by SteffenDE** [comment]
I didn't read in https://github.com/DaTrader/lv_bugs_0_19_5/pull/1#issuecomment-1938339400 that the existing items are removed, just that they aren't re-rendered, which is expected if their state did not change. If they get removed from the DOM this is indeed a bug, although a different one to what we previously discussed. Please open an issue in the LiveView repo for that with a corresponding reproduction.

**Comment by DaTrader** [comment]
> @DaTrader so basically, the behaviour you describe cannot be seen on this demo app? Are you serious? So are you asking us to run it if it does not show the bug?

Hold on a sec. Before going there check this: https://github.com/DaTrader/lv_bugs_0_19_5/pull/1#issuecomment-1938339400

Then check @SteffenDE's reply to it: https://github.com/DaTrader/lv_bugs_0_19_5/pull/1#issuecomment-1938432725

This whole discussion has emerged from these two comments linked above.

**Comment by DaTrader** [comment]
> I didn't read in [#1 (comment)](https://github.com/DaTrader/lv_bugs_0_19_5/pull/1#issuecomment-1938339400) that the existing items are removed, just that they aren't re-rendered, which is expected if their state did not change. If they get removed from the DOM this is indeed a bug, although a different one to what we previously discussed. Please open an issue in the LiveView repo for that with a corresponding reproduction.

OMG! We actually had a bug in our discussion :D I'm sorry for the ambiguity. This one may indeed be my bad.

**Comment by josevalim** [comment]
Sorry, we have spent enough times guessing. This is why we ask every single time for a reproduction, otherwise it is just a waste of everybody's time. This is time we could have spent fixing other bugs. This is not ok. Glad to continue once we can reproduce it.

**Comment by DaTrader** [comment]
> Sorry, we have spent enough times guessing. This is why we ask every single time for a reproduction, otherwise it is just a waste of everybody's time. This is time we could have spent fixing other bugs. This is not ok. Glad to continue once we can reproduce it.

I can take that. But it was a misunderstanding. In the end, I am happy you two agree that this is a bug.

**Comment by DaTrader** [comment]
@SteffenDE Back to the original question, unambiguous this time. Do you think you can find the underlying reason why those are removed - or as I said didn't render (I used that term because it was about the relationship between the stream component and the child component and because it was from the template that I inspected the ids when passing them to the child component and from the child template when getting rendered) or you need a repro?

**Comment by SteffenDE** [comment]
Yes, please. I currently have no idea why they would be removed even though they are included in the call to stream. Are they completely missing from the DOM?

**Comment by DaTrader** [comment]
> Yes, please. I currently have no idea why they would be removed even though they are included in the call to stream. Are they completely missing from the DOM?

Yes, they're completely missing. The IO.inspect/2 of their component ids from within the item component never gets invoked + I can't find them in the DOM.

**Comment by SteffenDE** [comment]
Do you see `cids_will_destroy` when you reset in the websocket messages?

**Comment by SteffenDE** [comment]
And is this any different in 0.20.5?

**Comment by DaTrader** [comment]
> Do you see `cids_will_destroy` when you reset in the websocket messages?

Where exactly should I look for this? (in the JSON objects received?)

**Comment by DaTrader** [comment]
nope, I don't see it anywhere

gotta split now. will be back in 20 min

**Comment by SteffenDE** [comment]
Okay then, no idea. Please try to create a repro and open a new issue in the LiveView repo.

**Comment by DaTrader** [comment]
@SteffenDE Been minimizing the app all day long (it's delicate because of my url-invalidation event driven MVC framework on top of LiveView). Hopefully the single file app will be available tomorrow.

Btw, I know see the bug tends to delete them ALL from the DOM (even the newly added one), but it keeps it because, catch this, it has the `phx-remove` attribute with `JS.hide` that somehow saves it from deletion (!!). If I remove the `phx-remove` attribute from the item, they all get deleted. 

In this reproduction I have removed some logic that used to prevent the visual hiding effect of the removed items, so now that the hiding effect is visible, it is clearly shown what happens: first the item is added positioned where it should be then immediately all others fade and get removed. Both these two steps occur in the same last client-side cycle after the last message received from the server.

**Pull request merged**
